# Generated by Django 5.0.4 on 2024-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/<function Account.folder_name at 0x000001455A976FC0>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/<function Account.folder_name at 0x000001455A976FC0>'),
        ),
    ]
