# Generated by Django 5.0.4 on 2024-07-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userimages_user_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic/<function Account.folder_name at 0x000001CFB7196FC0>'),
        ),
        migrations.AlterField(
            model_name='userimages',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/<function Account.folder_name at 0x000001CFB7196FC0>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/<function Account.folder_name at 0x000001CFB7196FC0>'),
        ),
    ]
