# Generated by Django 5.0.4 on 2024-07-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_user_cover_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimages',
            name='user_images',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/<function Account.folder_name at 0x0000026015F46FC0>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_cover_pic',
            field=models.ImageField(blank=True, null=True, upload_to='cover_pic/<function Account.folder_name at 0x0000026015F46FC0>'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/<function Account.folder_name at 0x0000026015F46FC0>'),
        ),
    ]
