# Generated by Django 5.0.4 on 2024-07-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
    ]
