# Generated by Django 5.0.4 on 2024-08-05 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='code',
            new_name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
