# Generated by Django 5.0.4 on 2024-08-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_code_coupon_coupon_code_remove_coupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limit_to_use_coupon',
            field=models.PositiveIntegerField(blank=True, default=100, null=True),
        ),
    ]
