# Generated by Django 5.0.4 on 2024-08-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_coupon_limit_to_use_coupon'),
        ('home', '0007_remove_variation_product_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, null=True, to='home.variation'),
        ),
    ]
