# Generated by Django 5.0.4 on 2024-08-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_variation'),
        ('home', '0007_remove_variation_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='home.variation'),
        ),
    ]
